//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NASEFLibrary.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MinistryCode
    {
        public int id { get; set; }
        public string code { get; set; }
        public bool used { get; set; }
        public Nullable<int> memberId { get; set; }
        public int ministryId { get; set; }
    
        public virtual Ministry Ministry { get; set; }
    }
}
