//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NASEFLibrary.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleDetailMember
    {
        public int id { get; set; }
        public Nullable<int> memberId { get; set; }
        public Nullable<int> roleDetailId { get; set; }
    
        public virtual Member Member { get; set; }
        public virtual RoleDetail RoleDetail { get; set; }
    }
}
